openapi: 3.0.0
info:
  title: self-web API
  version: 0.1.0
paths:
  /api/projects:
    get:
      summary: List projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
  /api/projects/{id}:
    get:
      summary: Get project by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
  /api/contact:
    post:
      summary: Contact form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactRequest'
      responses:
        '200':
          description: Message accepted
components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
    ContactRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        message:
          type: string
      required: [name, email, message]
